import{a as S,S as v,i}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const q="https://pixabay.com/api/",M="53429701-1a3d0b5c13468a36cfdf6d483";async function u(r,t){const o={key:M,q:r,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await S.get(q,{params:o})).data}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function m(r){const t=r.map(o=>`
<li class="gallery-item">
  <a href="${o.largeImageURL}">
    <img src="${o.webformatURL}" alt="${o.tags}" />
  </a>
  <div class="info">
    <p><b>Likes:</b> ${o.likes}</p>
    <p><b>Views:</b> ${o.views}</p>
    <p><b>Comments:</b> ${o.comments}</p>
    <p><b>Downloads:</b> ${o.downloads}</p>
  </div>
</li>`).join("");f.insertAdjacentHTML("beforeend",t),P.refresh()}function R(){f.innerHTML=""}function g(){p.classList.remove("is-hidden")}function y(){p.classList.add("is-hidden")}function L(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}const w=document.querySelector(".form"),B=document.querySelector("input[name='search-text']"),E=document.querySelector(".load-more");let a="",s=1,d=0;w.addEventListener("submit",$);E.addEventListener("click",O);async function $(r){if(r.preventDefault(),a=B.value.trim(),!a){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}s=1,R(),b(),g();try{const t=await u(a,s);if(d=t.totalHits,t.hits.length===0){i.error({title:"No results",message:"Sorry, no images match your search query.",position:"topRight"});return}m(t.hits);const o=Math.ceil(d/15);s<o&&L()}catch{i.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{y(),w.reset()}}async function O(){s+=1,b(),g();try{const r=await u(a,s);m(r.hits),x();const t=Math.ceil(d/15);if(s>=t){i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}L()}catch{i.error({title:"Error",message:"Something went wrong during loading.",position:"topRight"})}finally{y()}}function x(){const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
