import{a as w,S,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const v="https://pixabay.com/api/",q="53429701-1a3d0b5c13468a36cfdf6d483";async function u(n,t){const o={key:q,q:n,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await w.get(v,{params:o})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),B=new S(".gallery a",{captionsData:"alt",captionDelay:250});function p(n){const t=n.map(o=>`
<li class="gallery-item">
  <a href="${o.largeImageURL}">
    <img src="${o.webformatURL}" alt="${o.tags}" />
  </a>
  <div class="info">
    <p><b>Likes:</b> ${o.likes}</p>
    <p><b>Views:</b> ${o.views}</p>
    <p><b>Comments:</b> ${o.comments}</p>
    <p><b>Downloads:</b> ${o.downloads}</p>
  </div>
</li>`).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function M(){f.innerHTML=""}function y(){m.classList.remove("is-hidden")}function g(){m.classList.add("is-hidden")}function $(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}const b=document.querySelector(".form"),E=document.querySelector("input[name='search-text']"),P=document.querySelector(".load-more");let i="",s=1,d=null;b.addEventListener("submit",O);P.addEventListener("click",x);async function O(n){if(n.preventDefault(),i=E.value.trim(),!i){a.warning({title:"Warning",message:"Please enter a search query!"});return}s=1,M(),L(),y();try{const t=await u(i,s);if(d=t.totalHits,t.hits.length===0){a.error({title:"No results",message:"Sorry, no images match your search query."});return}p(t.hits),d>15&&$()}catch{a.error({title:"Error",message:"Something went wrong. Try again later."})}finally{g(),b.reset()}}async function x(){s++,y();const n=await u(i,s);p(n.hits),H(),s*15>=d&&(L(),a.info({title:"End",message:"You've reached the end of search results."})),g()}function H(){const n=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
